### ISSUE TITLE
Window too big

### ISSUE THREAD

**Issue by BrokModding** [klamonte/jexer#1]
Hello. Your window is too big. Could you make it to be in size of normal console?

**Comment by crramirez** [comment]
Hello Chris, 

Jexer auto adjust to the terminal window and the windows inside it you specify the coordinates and you can get the terminal window ones. 

Can you submit an screenshot?

Regards

**Comment by BrokModding** [comment]
That zonk: [link to screen](http://scr.hu/0qmbh/5r908).

**Comment by crramirez** [comment]
I agree looks terrible. For any reason the included Terminal font with the
library  is not being used check that.

My other answer is still valid when you create the window you can specify
the size. But first fix the font problem. Check your java version as well

Regards

**Comment by BrokModding** [comment]
I put a font in folder but its still so big and ugly... I use java 8. and JDK 8.

**Comment by klamonte** [comment]
Are you executing it by running 'java -jar path/to/jexer.jar' ?  If not, then the font is likely not being picked up on the CLASSPATH.

jexer.io.SwingScreen is looking specifically for the file "terminus-ttf-4.39/TerminusTTF-Bold-4.39.ttf", and if not found falls back to the JDK's default monospaced font.  If that is happening there should also be a stack trace in stderr, if you are running from an IDE that might be showing up too.

You can try other fonts by modifying jexer.io.SwingScreen near line 312, or changing the FONTFILE constant at line 142.

**Comment by BrokModding** [comment]
At first, nothing shows me ;<
I dont use this as library, but i put source in my project and just ran the demo... Placing font dont changes my weird situatuion

**Comment by klamonte** [comment]
> but i put source in my project

This explains it.  The file "terminus-ttf-4.39/TerminusTTF-Bold-4.39.ttf" is not in the runtime CLASSPATH as seen by the project in your IDE.  If your project has a "resources" folder then you can create a "terminus-ttf-4.39" sub-folder in there and then put the "TerminusTTF-Bold-4.39.ttf" file inside that.

An example from a different project: https://cayenne.apache.org/docs/4.0/tutorial/ch02.html  In this case that project has a "src/main/resources" folder that they can put files in (last image).  Googling "eclipse resource folder classpath" brings up several other threads that may be of use.

**Comment by BrokModding** [comment]
Problem solved ;] thanks.
