### ISSUE TITLE
TDesktop component

### ISSUE THREAD

**Issue by klamonte** [klamonte/jexer#14]
Add a TDesktop that is a TWidget drawn underneath everything else.

**Comment by nikiroo** [comment]
It would be nice!

I was checking if "fullscreen" TWindows were possible (https://github.com/nikiroo/jexer/commits/fullscreen -- if you are curious), but such a widget could maybe replace the need.

And that "underneath everything else" could be handy.

Yet, fullscreen-able TWindows would mean you could add a "F11"-style command or an option in a downstream application to see all windows as fullscreen...

I'll see what it'll be like when I'll start to use it.

The goal is to use it on an old pine/alpine like UI project of mine I'm starting to work on again.

It currently uses another library, but I had some compilation/library difficulties with it at the time (i.e., no gcj, not just any JRE...).

**Comment by klamonte** [comment]
This implementation of TDesktop is convenient for putting buttons and radio boxes underneath everything, but won't work for keyboard input unless all windows are closed.

Filling out TApplication's API has been a nice bonus though, now one can do either "subclass-a-window to get buttons" or "TApplication.addWindow() and add your widgets to it from the outside".

Next is unclosable windows, and then back around to Scrollable API.
