### ISSUE TITLE
Resizing TList makes its disappear.

### ISSUE THREAD

**Issue by BrokModding** [klamonte/jexer#2]
Hello. I have that code:
`@Override
public void onResize(TResizeEvent e){
		if(e.getType() == Type.WIDGET){
			s.setX(e.getWidth() - 2);
            s.setHeight(e.getHeight() - 2);
		}
	}`
This code may resize TList (its name is s), but when i am trying to do it, TList disappears. How to fix it?

**Comment by crramirez** [comment]
Why s.setX instead of s.setWidth?

**Comment by BrokModding** [comment]
@crramirez When i change it into setWidth, list dont changes even if i resize window, but good start - wont disappear.

**Comment by BrokModding** [comment]
Solved: I need to repaint list by reflow ;]. Working code: `@Override
	public void onResize(TResizeEvent e){
		if(e.getType() == Type.WIDGET){
			s.setX(0);
			s.setWidth(e.getWidth()-2);
            s.setHeight(e.getHeight()-2);
            s.reflow();
		}
	}`

**Comment by crramirez** [comment]
Excellent
