### ISSUE TITLE
Problem reading font data

### ISSUE THREAD

**Issue by stefan-reich** [klamonte/jexer#23]
Hi, I love this. Turbo Pascal was my daily bread long ago.

There's an issue: I get "Problem reading font data." on startup (although it all displays fine).

[Demo program.](http://tinybrain.de/1011955) The font data should be in the CLASSPATH (terminus-ttf... something?).

**Comment by klamonte** [comment]
Thanks for checking it out!

jexer.backend.SwingTerminal is trying to load "terminus-ttf-4.39/TerminusTTF-Bold-4.39.ttf" in the CLASSPATH, and obviously not succeeding.  I'm not sure how your environment sets the classpath, so can't guide you on getting that fixed.  However, you can try to call SwingBackend.setFont() with another font and see if that works.  Something like:

```
SwingBackend backend = (SwingBackend) myApplication.getBackend();
backend.setFont(...);
```

**Comment by stefan-reich** [comment]
No problem, I'm really happy to have found something that I can use for terminal GUIs! Laterna (competing project) didn't cut it for me.

I managed to load the font in the way you described, thanks! However, it is so tiny: http://tinybrain.de/1012117

This is the situation without the Terminus font, which actually looks great (if maybe on the big side): http://tinybrain.de/1012118

**Comment by klamonte** [comment]
Yup, the font size can be changed.  Something like this should work:

```
SwingTerminal terminal = (SwingTerminal) getScreen();
terminal.setFontSize(22);
```
