### ISSUE TITLE
Application freezes when clicking window close icon

### ISSUE THREAD

**Issue by stefan-reich** [klamonte/jexer#24]
Sad to see a bug there... Title says it all. Application works fine until I click the TWindow's close icon, at which point the whole program freezes. No msg on console.

[Demo program.](http://tinybrain.de/1011956)

**Comment by klamonte** [comment]
Does this happen against git head too?  I recall seeing a similar bug right around the last release, I think it was something I had forgotten to check when implementing TDesktop.

**Comment by stefan-reich** [comment]
I built the latest version from git with Maven. Still seeing the same problem. Demo program at same URL. Screenshot after clicking close button: http://tinybrain.de/1012120

I'll be glad if you can fix this :)

If you'd like to run the demo program, just run this file: tinybrain.de/x30.jar

**Comment by klamonte** [comment]
I will give that a shot and see what I can do.  Sorry it will be a couple days though :( very busy at my normal day job.

**Comment by stefan-reich** [comment]
What do you do? Curious

**Comment by klamonte** [comment]
Day job is manufacturing engineering, we've been slammed with stuff.

Found this one though, and thanks again for reporting it.  The demo line "addWindow(new MyWindow(this));" was adding the window to the TApplication list twice, once in TWindow constructor and once again in MyApplication.  This confused things.  Renamed the TApplication.addWindow function.  (Might choose to make it package private in the future, but will wait for that.)

**Comment by stefan-reich** [comment]
Thanks! So I have to build from GitHub again?

**Comment by klamonte** [comment]
Don't have to if you don't want to.  Change the line in your client code from:

addWindow(new MyWindow(this));

...to

new MyWindow(this);

...and you should be good.
