### ISSUE TITLE
jexer in a linux tty

### ISSUE THREAD

**Issue by stullii** [klamonte/jexer#26]
I'm coding a program using jexer, testing it on Linux.
It looks good in an X terminal, but in a text mode console I run into some problems.
1> the default color theme looks very bad. e.g. modal windows are bright white on white. In an XTerm they are perfectly readable but in a tty there just is not enough contrast. Anyway I found how to fix this by changing the default color theme.
2> The double line drawing characters (window borders) and the shadows of the buttons are displayed incorrecty in the tty (they all are displayed as  a diamond character), while single line window borders (used by inactive windows) are OK. Everything is fine in Xterms. Any suggestion for this problem?

**Comment by klamonte** [comment]
The console setup will depend on your distro.  Fedora's defaults for console look fine, but Debian by default changes the console font to something that is missing the CP437 glyphs used by Jexer.  See if you have the 'setfont' program, and if so try running just 'setfont' with no arguments to get the kernel's defaults font (uni_vga).  Qodem's getting started page (http://qodem.sourceforge.net/getting_started/getting_started.html) near the bottom it has pointers for screen, font, and keyboard that gets into more of the technical details.

The bad news with Linux console though is lack of mouse support.  gpm has its own method of communicating to the host program (libgpm, which ncurses also knows how to use) which one cannot get to in pure Java.  (Thinking about it now, I've already got most of a translator program ready in the form of Qodem, a super-stripped down utility version of it could act as a GPM<-->X10 mouse gateway, which would then provide full xterm-like experience to the console.  Adding it to the Jexer wishlist...)

**Comment by stullii** [comment]
I am running Debian 9. I have setfont installed, but running it with no arguments I get this error:
`Cannot find default font
`
I tried loading some font (e.g.:`setfont Uni2-Fixed16`). The font is changed, but my jexer program is still displaying the same incorrect chars. I also tried adding the -m parameter as in:
`setfont Uni2-Fixed16 -m cp437`
but all I get is this error:
`mapscrn: cannot open map file _cp437_`
Not sure how to proceed... I'll try to find out how all this console font stuff works, but now I got to work on something else, I'll only be able to work on this in a few days. In the meantime, have you got any suggestion?
Maybe including my /etc/default/console-setup helps. I did not change it, it's the default I got with a debian install
```
# CONFIGURATION FILE FOR SETUPCON
# Consult the console-setup(5) manual page.
ACTIVE_CONSOLES="/dev/tty[1-6]"
CHARMAP="UTF-8"
CODESET="Lat15"
FONTFACE="Fixed"
FONTSIZE="8x16"

```

**Comment by stullii** [comment]
Looks Iike I found a fix :-)
In console-setup, I changed fontface and fontsize to empty strings. This way I get the kernel default font and my jexer program looks good:
```
# CONFIGURATION FILE FOR SETUPCON
# Consult the console-setup(5) manual page.
ACTIVE_CONSOLES="/dev/tty[1-6]"
CHARMAP="UTF-8"
CODESET="Lat15"
FONTFACE=""
FONTSIZE=""

```

**Comment by klamonte** [comment]
FYI I have another project (LCXterm) that now speaks libgpm and can convert that to X10 mouse protocol.  Jexer looked pretty good on the console, it had mouse support (dragging, wheel up/down) when I tested it just now.  Should have it uploaded later today.
