### ISSUE TITLE
Allow InputBox to have type OKCANCEL

### ISSUE THREAD

**Issue by BenBE** [klamonte/jexer#27]
Sometimes you need an user to be able to cancel the question of an input box.

Like when you create a simple "establish connection" dialog and want the user to input the target host:port. If the user chooses to not want to connect for some reason it should offer to do so in the UI.

The underlaying TMessageBox implementation that TInputBox re-uses already allows this, but unfortunately this is not passed on to the derived implementation of TInputBox (which hardcodes it to TMessageBox.Type.OK. Would be nice to at least be able to choose between OK and OKCANCEL here.

**Comment by klamonte** [comment]
Sounds good to me.  Will add some constructors to permit cancelling.
