### ISSUE TITLE
NPE in ECMA48Terminal.closeTerminal

### ISSUE THREAD

**Issue by BenBE** [klamonte/jexer#29]
From FindBugs:

```text
src/jexer/backend/ECMA48Terminal.java:512 Nullcheck of ECMA48Terminal.output at line 526 of value previously dereferenced in jexer.backend.ECMA48Terminal.closeTerminal() [Troubling(11), Normal confidence]
```

To be more precise: Disabling and restoring back to defaults can only reliably be done with
```java
// Disable mouse reporting and show cursor
output.printf("%s%s%s", mouse(false), cursor(true), normal());
output.flush();
```
after it is ensured that there's an output stream to write and flush. The simple fix probably is to duplicate the null check for `output!=null` from line 526 to cover these lines too.

**Comment by klamonte** [comment]
Ah, nice catch.  Thanks for reporting, will get this fixed.
