### ISSUE TITLE
NPE in TDirectoryTreeItem.onExpand

### ISSUE THREAD

**Issue by BenBE** [klamonte/jexer#30]
Taken from FindBugs:
```text
src/jexer/ttree/TDirectoryTreeItem.java:185 Possible null pointer dereference in jexer.ttree.TDirectoryTreeItem.onExpand() due to return value of called method [Troubling(13), Normal confidence]
```

The issue here lies with java.io.File.listFiles possibly returning null (cf. JavaDoc for details).

The fix is to check the null return before entering the loop over all files in the directory.

**Comment by klamonte** [comment]
Thanks for the report, will fix.
