### ISSUE TITLE
Synchronization issue regarding timers

### ISSUE THREAD

**Issue by BenBE** [klamonte/jexer#31]
While we are at it, there's another noteworthy issue FindBugs reported:

```text
src/jexer/TApplication.java:1217 Synchronization on TApplication.timers in futile attempt to guard it [Scary(6), Normal confidence]
```

The issue here is quite simple and easy to fix. As synchronize operates on the object being synchronized to, not the field being synchronized there's actually a chance for some race condition (hitting while the field has been re-assigned but before the monitor is released.

This can be easily avoided, by retaining the original Timer list, clear it and addAll the timers that should be kept.
```diff
diff --git a/src/jexer/TApplication.java b/src/jexer/TApplication.java
index 34f1559..83ab862 100644
--- a/src/jexer/TApplication.java
+++ b/src/jexer/TApplication.java
@@ -1205,7 +1213,9 @@ public class TApplication implements Runnable {
                     keepTimers.add(timer);
                 }
             }
-            timers = keepTimers;
+
+            timers.clear();
+            timers.addAll(keepTimers);
         }
 
         // Call onIdle's
```

**Comment by klamonte** [comment]
Thank you for reporting this, will get this fixed.

I definitely value race condition reports.  Jexer originated as a D-language project that used fibers instead of true threads, so I would not be surprised if in transliteration I left more of these issues around.
