### ISSUE TITLE
Tile should inform windows they have been resized.

### ISSUE THREAD

**Issue by jkbbwr** [klamonte/jexer#34]
As above.

**Comment by jkbbwr** [comment]
I think so, Im probably going to be annoying over the next few weeks (and might get my hands dirty myself) because I am contemplating using this in a project I am working on

**Comment by klamonte** [comment]
If annoying means more bug reports, then I will be happy to be annoyed. :)

**Comment by jkbbwr** [comment]
Im also pulling head using jitpack so I get changes as they happen.
