### ISSUE TITLE
Migrate off github

### ISSUE THREAD

**Issue by klamonte** [klamonte/jexer#35]
The Microsoft acquisition of github is unacceptable in the long term.

Decide on a new hosting platform before the next release (which will be on Maven as requested in #20 ).

**Comment by klamonte** [comment]
Looking at gitlab as the new home.  Plan is to finish up the next release on github, closing most of the open issues, then move to gitlab, then publish on maven.

**Comment by oising** [comment]
Will the source as it exists on github now continue to remain licensed under MIT, Kevin?

**Comment by klamonte** [comment]
GitLab repo now visible to public:  https://gitlab.com/klamonte/jexer

What's there now: LOTS of bug fixes, performance improvements, and image support (including sixel output on xterm).

Working on #20 also, in prep for new release + release on Maven central.  Don't know yet if Maven will be able to fix my SCM URLs now or not, that will determine whether or not this repo is fully deleted or just left as a sync point to get into Maven for the future.

**Comment by klamonte** [comment]
Maven release is done, GitLab is running fine, closing this one.
