### ISSUE TITLE
Improvement to support full-width characters (like CJK characters)

### ISSUE THREAD

**Issue by moontide** [klamonte/jexer#36]
Thanks for bring this nice turbo vision style library to the world.

Chinese characters usually take two characters width to display, this messed the UI.
Screenshot:
![jexer-0.0.5 与汉字显示](https://i.imgur.com/TpajNwP.png)

**Comment by klamonte** [comment]
Thank you for reporting this.

I will have to do some thinking about the right way to solve this one.  I would like to do this in a general-purpose way, not just double-width but potentially double-height as well (that would give TTerminal true VT100 double-width/height support too).

**Comment by klamonte** [comment]
@moontide Do you have a preferred font with good coverage of full-width characters?

Now that I have image support, I might be able to at least render the full-width characters correctly.  It would be a start anyway.

**Comment by moontide** [comment]
> @moontide Do you have a preferred font with good coverage of full-width characters?

My favorite font is 'WenQuanYi Zen Hei Sharp' (‘文泉驿点阵正黑’ in Chinese), it's a bitmap font which is actually '[WenQuanYi Bitmap Song](http://wenq.org/wqy2/index.cgi?BitmapSong)' font embedded in '[WenQuanYi Zen Hei](http://wenq.org/wqy2/index.cgi?ZenHei)' font.

The webpage of WenQuanYi font project said it covers all characters in GB2312/Big5/GBK/GB18030 character sets. But I don't know is it good enough for other languages. Maybe adobe-source or google-noto fonts is a better choice, but they don't provide bitmap fonts.

WenQuanYi Zen Hei font can be downloaded from sourceforge.net.
https://sourceforge.net/projects/wqy/files/wqy-zenhei/

> Now that I have image support, 

Whaaaaaat? Image support in jexer, that's amazing!

> I might be able to at least render the full-width characters correctly. It would be a start anyway.

Do you mean render characters as an image or something else?
When rendering characters as an image, it could be a trouble when changing font size in terminal emulator.

**Comment by klamonte** [comment]
> WenQuanYi Zen Hei font can be downloaded from sourceforge.net.
> https://sourceforge.net/projects/wqy/files/wqy-zenhei/

Thank you, I will check it out!

> > Now that I have image support,

> Whaaaaaat? Image support in jexer, that's amazing!

Yup, we have image support. :)  It's over on the GitLab repo now: https://gitlab.com/klamonte/jexer , there are some screenshots there.  If you want more of the nitty-gritty, the tail end of the writeup [here](https://jexer.sourceforge.io/evolution.html) discusses sixel in Jexer.  I have never heard of a TUI with mixed text/sixel support until now, Jexer might be the first of its kind.  (The other projects appear to render to bitmap, then convert the whole bitmap to sixel.)

Credit for the idea actually comes from your feature request here.  I've been wanting image support for a few years, but the request for CJK support pushed it into the front.

> > I might be able to at least render the full-width characters correctly. It would be a start anyway.

> Do you mean render characters as an image or something else?

Initially, rendering an as image for Xterm.  (Swing would be drawing from the font directly, so would look correct but Jexer would internally think of it as image and not text.)  If I can get a smooth rendering of full/double-width now, then I also get true VT100 support in the widget, and afterwards I can see about really understanding the difference between narrow/wide on screen and handling full-width text entry and mouse pointer.  Once Jexer really understands narrow/wide, CJK could be an exposed option to use either native font or rendered, a bit like Xterm's ability to select from multiple fonts.

> When rendering characters as an image, it could be a trouble when changing font size in terminal emulator.

jexer.backend.ECMA48Terminal now asks xterm for the window size, and figures out the text cell dimensions.  Hopefully it will be straightforward to detect the font size change.

Sidenote: on MultiBackend, the smallest text cell size of all the screens is returned for TImage, which it uses to figure out how to break up the image into cell pieces.  This has the interesting effect that one can see an image in 24-bit on Swing and sixel palette on xterm at the same time:
![swing_and_xterm_images](https://user-images.githubusercontent.com/4357501/53094505-ea9cb280-34df-11e9-9a83-8c630b942c2d.png)

**Comment by klamonte** [comment]
Going to follow up tracking of this over at GitLab: https://gitlab.com/klamonte/jexer/issues/35
