### ISSUE TITLE
NegativeArraySizeException when maximize terminal window

### ISSUE THREAD

**Issue by b0DW** [klamonte/jexer#37]
NegativeArraySizeException when maximize terminal window when using connection over TCP
![screenshot from 2019-02-05 11-32-16](https://user-images.githubusercontent.com/39428411/52261235-c49cdd00-2939-11e9-9837-d97ee0356c9c.png)

**Comment by klamonte** [comment]
Thank you for reporting this.  Will look into it.

**Comment by klamonte** [comment]
Closing this one.  Fix is in git head here and in the newest repo at https://gitlab.com/klamonte/jexer .
