### ISSUE TITLE
twindow scrolling

### ISSUE THREAD

**Issue by Jeakun** [klamonte/jexer#4]
hi. good morning. klamonte.

TWindow's scroll support?

**Comment by klamonte** [comment]
What is the question here?

**Comment by Jeakun** [comment]
sorry,

I did not find a place to ask questions.

**Comment by crramirez** [comment]
Ok jeakun, Kevin is just telling you to elaborate your question better
because we don't understand what you are asking for

**Comment by Jeakun** [comment]
I'm currently using jexer.
As you configure the UI, TWindow does not support scrolling.
I tried to fix it myself, but it failed.
So, I have written a question here to see if there is a way to be supported.

Can I get help?

**Comment by klamonte** [comment]
TWindow is just a container widget for other things.  Currently, to get scrolling behavior you have to add TVScroller or THScroller to TWindow and change their X/Y positions as TWindow is resized to keep them on the edge.

TText shows an example of a window with both horizontal and vertical scrollbars.  TTerminalWindow has just a single vertical scrollbar.  The reflow() function in each one shows the logic of creating the scrollbar and changing its location to stay on the outside edge of the window.

The overall API is still a work in progress.  This would be a good time to either add a scrollbar flag to TWindow, and/or create a TScrollingWindow class that does reflow() automatically.

**Comment by Jeakun** [comment]
Let me think about TScrollingWindow.
But maybe not. I am.

We'll wait for work in progress.

Thank you for developing these APIs. Kevin.

bye.

**Comment by klamonte** [comment]
FYI a Scrollable interface with TScrollableWidget and TScrollableWindow classes is in the works, should be uploaded later tonight.  These classes handle the resize and expose the scrollbar functions to callers.

**Comment by klamonte** [comment]
Commit https://github.com/klamonte/jexer/commit/56661844475522242093c8858ceb20fb15589da5 has a common interface to scrollbar support.
