### ISSUE TITLE
Z-Order when handling upo/down mouse events on widgets

### ISSUE THREAD

**Issue by nikiroo** [klamonte/jexer#7]
Hello,

I'm playing around with your library (0.0.4, if it changes anything), and found out a few things I'd like to change.
So I thought you may be interested.

The first one is a small bug: in **TWidget** **onMouseUp**/**Down** handling code, you pass the event to the first child that accepts it.
But.
The children are drawn in reverse order (as it should -- the last one visually override the previous widgets).

So, while it works fine with the keyboard, the mouse events (up/down only, since move is sent to all widgets anyway) are sent to the invisible widgets.

An example of how you can see the problem: if you have a TText covered by a TButton (or, it seems, even if the TText is just ONE LINE above the TButton without any space between the two), you can see but cannot mouse-click on said button.
I attached a screenshot (though I use a modified version of TText, but the behaviour is the same in this case):
 ![example](https://user-images.githubusercontent.com/8403104/27681214-bb9fe740-5cbe-11e7-920c-ecbacb39f041.png)

.

A simple 
```
for (int i = children.size() - 1 ; i >= 0 ; i--) {
TWidget widget = children.get(i);
```
Instead of the current
`for (TWidget widget: children) {`
in those 2 mouse handling functions in **TWidget.java** will fix this.

Thanks for the library,
Niki

**Comment by nikiroo** [comment]
(See pull request https://github.com/klamonte/jexer/pull/12)

**Comment by klamonte** [comment]
#13 is opened to track supporting several options for mouse behavior.
