### ISSUE TITLE
Request for UNCLOSABLE windows

### ISSUE THREAD

**Issue by nikiroo** [klamonte/jexer#8]
Hello,

Just a second note, would it be possible to add UNCLOSABLE windows?
(And also public **maximize()** and **restore()** instead of private?)

The idea would be to have a maximized "main" window that will always be present on screen.

A working solution (the one I currently use) would be:

**TWindow.java**:
```
+    /**
+     * Window cannot be closed (default no, can be closed).
+     */
+    public static final int UNCLOSABLE  = 0x08;
```

```
+     /**
+     * This window cannot be closed.
+     * @return TRUE if it cannot be closed
+     */
+    public boolean isUnclosable() {
+               return (flags & UNCLOSABLE) != 0;
+       }
```

**TWindow.java** in **public void draw()** just under **// Draw the close button**:
`if (!isUnclosable()){`
(enclosing the code up until but not included to: **// Draw the maximize button**)

**TWindow.java** in **mouseOnClose()** first line:
`+       if (((flags & UNCLOSABLE) == 0)) {`
(enclosing the code up until but not included to: **return false**)

**TApplication.java** in **closeWindow(final TWindow window)** first line:
```
+       // Only allow to close a non-closable window when exiting the application
+        if (!quit && window.isUnclosable())
+                return; 
```

**TApplication.java** in **closeAllWindows()** replace:
```
-        while (windows.size() > 0) {
-            closeWindow(windows.get(0));
```
by:
```
+        for (TWindow window : windows) {
+            closeWindow(window);
```

Of course it is just an example implementation (too small to actually offer a patch file for), but it would be appreciated :)

Thank you,
Niki

**Comment by nikiroo** [comment]
Well, nothing is too small for a pull request, actually:
See pull request https://github.com/klamonte/jexer/pull/11

**Comment by klamonte** [comment]
Thanks for the PR!  I will be reviewing TWindow's external API this week and include unclosability.

Question: are you expecting that an unclosable window get its onClose() called at application exit, or not?   I can see arguments either way, not sure what makes the most sense for your application.

**Comment by nikiroo** [comment]
You're welcome!

Yes, I would expect it to be called since if I don't want the code to run, I can just not add the code -- the "uncloseablility" of the window cannot be changed, only set at creation time.

Also, please take the latest commit in the branch, I made a stupid mistake and try to remove a window from a list when I access it in TApplication#closeAllWindows()...
